;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
# background = #f2000000
background = #f2050505
background-alt = #f2111111
foreground = #ffffff
primary = #ba68c8
secondary = #ba68c8
alert = #A54242
disabled = #888888

[bar/mybar]
width = 100%
height = 20px
radius = 0
bottom = true

dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2px

; border-size = 4pt
; border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 5px

separator = |
separator-foreground = ${colors.disabled}

font-0 = Monaco 9:size=12;2
# font-0 = Terminess Nerd Font Propo:size=9;2
font-1 = Terminess Nerd Font Propo:size=9;2
font-2 = Noto Sans CJK JP:size=9;3

# font-0 = Gohu GohuFont:size=8;2
# font-1 = Terminess Nerd Font Propo:size=9;2

; modules-left = xworkspaces xwindow
; modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth battery date systray

modules-left = xworkspaces xwindow
modules-right = spotify filesystem memory cpu xkeyboard pulseaudio wlan eth battery date systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 0px
tray-spacing = 4px
tray-size = 16px

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 5px

label-occupied = %name%
label-occupied-padding = 5px

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 5px

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 5px

[module/xwindow]
type = internal/xwindow
label = %title:0:55:…%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

; label-mounted =  %{F#FFFFFF}%mountpoint%%{F-} %percentage_used%%
label-mounted =  %{F#FFFFFF}%mountpoint%%{F-} %percentage_used%%
; label-mounted =  %{F#FFFFFF}%mountpoint%%{F-} %percentage_used%%
; label-mounted =  %{F#FFFFFF}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.foreground}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = 󰖁 %percentage%%
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = 󰌌 %layout%
label-layout-foreground = ${colors.foreground}

label-indicator-padding = 1
label-indicator-margin = 0
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = <label-disconnected>

[module/wlan]
inherit = network-base
interface-type = wireless
; label-connected =  %{F#FFFFFF}%ifname%%{F-} %essid% %local_ip%
; label-disconnected =  %{F#FFFFFF}%ifname%%{F#707880} disconnected
label-connected = 󰖩 %essid:0:10:…% %signal%%
label-disconnected = %{F#707880}󰖪

[module/eth]
inherit = network-base
interface-type = wired
label-connected = 󰈀 %{F#FFFFFF}%ifname%%{F-} %local_ip%
# label-disconnected = 󰈀 %{F#FFFFFF}%ifname%%{F#707880} disconnected
label-disconnected =

[module/date]
type = internal/date
interval = 1

date = 󰥔 %H:%M
; date = %H:%M
date-alt = 󰃭 %Y-%m-%d 󰥔 %H:%M:%S

label = %date%
label-foreground = ${colors.foreground}

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 97

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 5

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
;format-low = <label-low> <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full =  100%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = BATTERY LOW

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
[module/spotify]
type = custom/script
tail = true
interval = 1
# prefix symbol is shown before the text
format-prefix = " "
format = <label>
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh

[module/spotify-prev]
type = custom/script
exec = echo "<previous-song-symbol>"
format = <label>
click-left = playerctl previous -p spotify

[module/spotify-play-pause]
type = custom/ipc
hook-0 = echo "<playing-symbol>"
hook-1 = echo "<pause-symbol>"
initial = 1
click-left = playerctl play-pause -p spotify

[module/spotify-next]
type = custom/script
exec = echo "next-song-symbol"
format = <label>
click-left = playerctl next -p spotify
